const PROPHECIES = [
  // ===== 科技与通讯 =====
  { id: 1, cat: "tech", q: "未来人类出去旅游，是乘坐什么交通工具？", a: "科技发展并没有想象中那么遥不可及。2048年以前，旅行仍靠飞机与磁悬浮列车。" },
  { id: 15, cat: "tech", q: "人类可以去火星旅行了吗？", a: "不能。但是卫星可以抵达并环绕四周，有一家美国的巨型公司开发了可以体验火星上见闻的智慧视角工程，有点类似你们现在使用的虚拟现实体验，但智慧视角工程更为身临其境。" },
  { id: 33, cat: "tech", q: "移动通讯技术的进步改变了什么？以后会有6G 7G 8G这样吗？", a: "7G之后，就不再以G命名。因为已经到了另外一个阶段，时间是2048年以后。", year: 2048, status: "pending" },
  { id: 38, cat: "tech", q: "以后最新兴的行业是什么？", a: "2030年以后，会是人工智能与跨行业者的结合，就是精通人工智能开发与编程的各个行业。另外游戏业从2035年进入了另外一个阶段。", year: 2030, status: "partial", verdict_zh: "AI行业确实在2023年后爆发（ChatGPT等），人工智能与各行业结合的趋势已经开始显现。", verdict_en: "AI industry indeed exploded after 2023 (ChatGPT etc.), the trend of AI combining with various industries has become evident." },
  { id: 43, cat: "tech", q: "是否存在全息旅游和全息游戏？", a: "2035年开始出现第一款这样的游戏，在中国。", year: 2035, status: "pending" },
  { id: 47, cat: "tech", q: "机器人贵吗？可以制作的跟真人一样吗？", a: "2035年起，机器人广泛应用于交互游戏。2038年强人工智能量化生产。定制需要取得复杂的授权与法律条文。", year: 2035, status: "pending" },
  { id: 49, cat: "tech", q: "什么时候机器人可以广泛应用，像手机一样？", a: "2038年以后。", year: 2038, status: "pending" },
  { id: 107, cat: "tech", q: "从5G到7G用了29年？", a: "是的，在后的比在前的复杂。" },
  { id: 109, cat: "tech", q: "游戏开源吗？拿什么编程语言写的？", a: "交互游戏是以打印技术、眼睛科学、机器人定制为三大根基。" },
  { id: 110, cat: "tech", q: "2060年，流行什么科学理论？量子力学怎样了？", a: "观察者问题在2049年解决了。时间存在的意义被解决了。", year: 2049, status: "pending" },
  { id: 173, cat: "tech", q: "你现在用什么发豆瓣的？手机的话什么款？", a: "30年代手机会成为历史。", year: 2039, status: "pending" },
  { id: 175, cat: "tech", q: "手机成为历史？那你们在未来替代手机功能的是什么呢？", a: "最早称之为物联，后来是芯片植入。" },
  { id: 201, cat: "tech", q: "小米公司在30年代发展如何？还存在吗？", a: "冷战是全面的。没有一个科技公司能逃避。" },
  { id: 212, cat: "tech", q: "量子力学在未来是否被解释清楚了？", a: "是的。观察者问题被解决了。" },
  { id: 222, cat: "tech", q: "语言是如何变得无障碍的？", a: "通过物联网同步感知消除语言障碍。" },
  { id: 228, cat: "tech", q: "量子力学揭示了什么？", a: "观察者即创造者。" },
  { id: 243, cat: "tech", q: "会出现不需要携带的新乐器吗？", a: "虚拟吉他、萨克斯等。" },
  { id: 273, cat: "tech", q: "量子力学是否导致世界变化？", a: "后来叫了不同的名字。" },

  // ===== 地缘政治与战争 =====
  { id: 2, cat: "politics", q: "社会主义建设到哪一步了？", a: "我来的年代，朝鲜、古巴都已不再走这条道路。" },
  { id: 12, cat: "politics", q: "美国还存在吗？特朗普能连任吗？", a: "仍然存在。特朗普会继续连任，但他将面临来自亲人与反对他的人给与的巨大压力。", year: 2020, status: "partial", verdict_zh: "特朗普2020年未能连任，但2024年再次当选。预言部分正确——他确实面临巨大压力。", verdict_en: "Trump lost in 2020 but won again in 2024. Partially correct — he did face enormous pressure." },
  { id: 20, cat: "politics", q: "哪里的战争？", a: "牵扯到全球的两个世界文明，地点是在三个大洲交界。我只能说这么多。" },
  { id: 24, cat: "politics", q: "那时候空气质量会好吗？我们是不是第一大强国？", a: "空气没有更好。第一大强国在西方。" },
  { id: 40, cat: "politics", q: "小康实现了吗？", a: "只停留于历史的一个词汇。" },
  { id: 106, cat: "politics", q: "中国在第三次世界大战处于什么位置？", a: "与美国欧盟以色列对抗。与中东印度联盟。" },
  { id: 113, cat: "politics", q: "想问下台湾何时回归？", a: "2022年–2023年会有一次事件。", year: 2023, status: "partial", verdict_zh: "2022年佩洛西访台引发台海危机，中国大规模军演。确实发生了重大事件，但并非回归。", verdict_en: "Pelosi's 2022 Taiwan visit triggered a cross-strait crisis with large-scale Chinese military drills. A major event did occur, but not reunification." },
  { id: 119, cat: "politics", q: "俄罗斯呢？", a: "表面中立。" },
  { id: 120, cat: "politics", q: "与中东印度联盟的话，中东的宗教问题对中国有没有伤害？", a: "朝鲜不久会有变动。" },
  { id: 131, cat: "politics", q: "我国出现女主席了吗？", a: "如果你问的是国家元首，并没有。但其他组织的女主席是有的。" },
  { id: 133, cat: "politics", q: "日本还存在吗？", a: "存在，但失去一半。" },
  { id: 140, cat: "politics", q: "战争都是因何而起的呢？", a: "宗教与文明的冲突。" },
  { id: 153, cat: "politics", q: "请问中国最近的一次大规模战争是什么时候？", a: "不在中国本土。在三大洲交界。" },
  { id: 156, cat: "politics", q: "中国是从2019年开始明显走下坡路吗？", a: "会走民族主义道路。" },
  { id: 162, cat: "politics", q: "全世界哪些地方适合定居呢？", a: "欧洲将是战争发源地。" },
  { id: 169, cat: "politics", q: "战争的形式还是短兵相接炮火纷争吗？", a: "尸首成堆，血流成河。" },
  { id: 188, cat: "politics", q: "日本迁哪里去了？", a: "迁都冈山。" },
  { id: 190, cat: "politics", q: "欧洲发展怎么样了？", a: "因为中东宗教渗入，整体显得软弱无力，直到一个强盛的人出现。战乱因他而起，也到他为止。世界因此震动，一切改变。" },
  { id: 192, cat: "politics", q: "请问过几天G20峰会之后，中国会发生什么样的改变吗？", a: "日韩表面中立。" },
  { id: 200, cat: "politics", q: "法国的未来怎么样？", a: "软弱。" },
  { id: 202, cat: "politics", q: "特朗普的历史意义是什么？", a: "引发了第二次冷战。" },
  { id: 203, cat: "politics", q: "哪个国家GDP最高？", a: "2048年前中国和美国交替。" },
  { id: 207, cat: "politics", q: "世界大战是否发生在2048年？持续多久？", a: "超过三年。", year: 2048, status: "pending" },
  { id: 225, cat: "politics", q: "巴西会怎样？", a: "混乱。" },
  { id: 226, cat: "politics", q: "西班牙的情况如何？", a: "与欧洲共命运。" },
  { id: 227, cat: "politics", q: "描述东亚冲突和救赎之路？", a: "局部战争以和平协议结束。" },
  { id: 233, cat: "politics", q: "蔡英文什么时候去世？", a: "2039年。", year: 2039, status: "pending" },
  { id: 245, cat: "politics", q: "中加关系什么时候变得紧张？", a: "2019年。", year: 2019, status: "verified", verdict_zh: "2018年底孟晚舟在加拿大被捕，2019年中加关系急剧恶化，互相驱逐外交官。完全应验。", verdict_en: "Meng Wanzhou was arrested in Canada in late 2018, and China-Canada relations deteriorated sharply in 2019 with mutual diplomatic expulsions. Fully verified." },
  { id: 247, cat: "politics", q: "公务员2048年后还稳定吗？", a: "公务员2048年后不再存在。", year: 2048, status: "pending" },
  { id: 250, cat: "politics", q: "极端意识形态会卷土重来吗？", a: "不会，但管控增加。" },
  { id: 274, cat: "politics", q: "基因编辑和阶级体系是否改变？欧洲主要问题在哪？", a: "西欧。" },
  { id: 280, cat: "politics", q: "联合国还有意义吗？", a: "逐渐失去意义，无法团结。" },
  { id: 281, cat: "politics", q: "俄罗斯在世界大战中的角色？", a: "表面中立，暗中推动战争。" },

  // ===== 经济与金融 =====
  { id: 5, cat: "economy", q: "你在2060年买得起房子吗？", a: "2060年房屋不是贵重物质。" },
  { id: 6, cat: "economy", q: "100块可以买到什么呀？", a: "2060年的货币没有'块'。" },
  { id: 11, cat: "economy", q: "沪深上证指数到20000了吗？", a: "没有。" },
  { id: 17, cat: "economy", q: "房产会泡沫吗？", a: "我出生的时候，房子不是贵重物品。老人们聊天说过从前房子很贵，但我很难想象。" },
  { id: 21, cat: "economy", q: "你带钱了吗？", a: "没有。因为在2060年，纸是奢侈品。一切财富都将数字化。" },
  { id: 37, cat: "economy", q: "交通费贵吗？房价不高了，那什么是贵的？", a: "2060年的公共交通是免费的。日常比较昂贵的消费品是水果牛奶，只有富有的人可以吃。房子是极速工具建造，除非特别富有的人指定用木头作为材质，一般人都可以申请建造自己的房屋，成本都很廉价。" },
  { id: 125, cat: "economy", q: "请问在20-30年代转行就业适宜且能拿到最大红利的行业是？", a: "20年代中后期从事生机农业。我印象中从事生机农业生产者的亲戚都很富有。" },
  { id: 223, cat: "economy", q: "比特币在你那个时代值多少？", a: "不再存在。", year: 2060, status: "pending" },
  { id: 253, cat: "economy", q: "金融的意义是否降低？拜金主义是否加重？", a: "一个小时内，全球金融系统崩溃后，人们将不再拜金，转而追求内在文明。" },
  { id: 258, cat: "economy", q: "金融系统怎么可能在一小时内崩溃？", a: "那个时代的人也不相信。不再回答个人问题。" },

  // ===== 社会与生活 =====
  { id: 7, cat: "society", q: "国家开始分配对象了吗？", a: "没有。" },
  { id: 16, cat: "society", q: "结婚率多少？", a: "各个国家和民族不太一样。大部分国家结婚率偏低。" },
  { id: 18, cat: "society", q: "未来地球有多少人口啊？", a: "2047年有80亿。2060年减少到53亿。", year: 2047, status: "pending" },
  { id: 19, cat: "society", q: "（人口减少的原因）", a: "战争、地震、饥荒、海啸。" },
  { id: 28, cat: "society", q: "那时候人的平均寿命是多少？人心普遍更好还是更坏？", a: "各个国家不一样。平均寿命最高的是澳大利亚。人心好的会更好，坏的会更坏。善良的事有，恐怖的事更多。" },
  { id: 46, cat: "society", q: "人文学科的发展如何？性别平等问题是否有所改变？", a: "人文倾向于在全球不同文明中找到共荣理论，但仍然失败。在某些国家和地区，歧视女性仍然存在。在另一些地区，女性主义强盛，但也导致混乱。" },
  { id: 108, cat: "society", q: "猫狗宠物和其他动物你们那个年代还存在吗？", a: "继续存在。但动物和人的关系有质的改变。" },
  { id: 112, cat: "society", q: "动物和人质的改变，您能具体说说么？", a: "动物与人和平相处。动物之间也是如此。" },
  { id: 123, cat: "society", q: "请问纸质书是否彻底消失了？", a: "纸质书没有彻底消失，但不再普及，是作为收藏品和拍卖品。" },
  { id: 126, cat: "society", q: "可以不去上班在家工作吗？", a: "在家办公在20年代就有很多行业都实现了。", year: 2025, status: "verified", verdict_zh: "2020年新冠疫情迫使全球大规模远程办公，此后远程/混合办公成为常态。完全应验。", verdict_en: "The 2020 COVID pandemic forced global remote work adoption, which has since become the norm. Fully verified." },
  { id: 143, cat: "society", q: "你那时候的人平均寿命多少？", a: "因为把全球战争、大地震因素纳入，比现在要低很多。" },
  { id: 150, cat: "society", q: "请问阿茨海默症有解了吗？什么时候被攻克？", a: "战争之后。记忆并不会遗忘，只是被封存了。" },
  { id: 160, cat: "society", q: "上海全部垃圾分类是什么时候开始的？", a: "我出生的时候就有垃圾分类。", year: 2019, status: "verified", verdict_zh: "上海2019年7月1日正式实施垃圾分类。KFK发帖时间为2019年6月，一个月后上海即开始垃圾分类。应验。", verdict_en: "Shanghai officially implemented waste sorting on July 1, 2019. KFK posted in June 2019, one month before it started. Verified." },
  { id: 165, cat: "society", q: "你的名字KFK是你全名的缩写吗？", a: "不是。30年代以后，中国四个字的名字开始盛行。" },
  { id: 176, cat: "society", q: "楼主是文科生吧？", a: "30年代不再分文理。" },
  { id: 177, cat: "society", q: "我嫁给吴亦凡了吗？", a: "这个明星在我童年的记忆里存在过。上了一个让人印象深刻的热点新闻。", year: 2021, status: "verified", verdict_zh: "吴亦凡2021年因涉嫌强奸罪被捕，成为轰动全国的热点新闻。KFK说他'上了一个让人印象深刻的热点新闻'，完全应验。", verdict_en: "Kris Wu was arrested in 2021 for alleged rape, becoming nationwide headline news. KFK said he 'made an impressive headline news', fully verified." },
  { id: 179, cat: "society", q: "那你为什么会有台湾人的口癖啊？", a: "未来人东亚文化上有高度融合，可能你们不习惯，但你们的后辈如果在大城市生活，都会这样讲话。" },
  { id: 187, cat: "society", q: "2060年还有新浪微博吗？", a: "没有。" },
  { id: 195, cat: "society", q: "人口80亿减到53亿主要是因为疾病还是战争啊？", a: "都有。" },
  { id: 205, cat: "society", q: "30年代人人都是博士学历吗？", a: "博士在30年代中国不再受到尊重。" },
  { id: 215, cat: "society", q: "中国娱乐行业的质量如何？", a: "质量很差。" },
  { id: 216, cat: "society", q: "中国同性婚姻合法了吗？", a: "2060年前在某些地区合法。" },
  { id: 217, cat: "society", q: "中国娱乐会进步和开放吗？", a: "不会。" },
  { id: 230, cat: "society", q: "婚姻和性别关系如何变化？", a: "中国整体仍然相对保守。" },
  { id: 231, cat: "society", q: "你看过猫和老鼠吗？", a: "我的童年没有。但看过《小猪佩奇》。" },
  { id: 234, cat: "society", q: "同性婚姻什么时候合法化？", a: "台湾2019年已经合法化了。", year: 2019, status: "verified", verdict_zh: "台湾于2019年5月24日正式实施同性婚姻法，成为亚洲首个同性婚姻合法化的地区。完全应验。", verdict_en: "Taiwan officially legalized same-sex marriage on May 24, 2019, becoming the first in Asia. Fully verified." },
  { id: 235, cat: "society", q: "为什么用繁体字？", a: "30年代全国会有恢复繁体字的运动。" },
  { id: 238, cat: "society", q: "性别平等什么时候实现？", a: "战争之前不会。" },
  { id: 241, cat: "society", q: "律师、会计、公务员、教师、医生还存在吗？", a: "教师和医生持续到2060年。" },
  { id: 244, cat: "society", q: "蟑螂灭绝了吗？", a: "一直存在。" },
  { id: 257, cat: "society", q: "我能结婚吗？", a: "两次。" },
  { id: 263, cat: "society", q: "不结婚的老人怎么生活？", a: "老年中心，居民成为股东。" },
  { id: 265, cat: "society", q: "中国什么时候安乐死合法化？", a: "永远不会。" },
  { id: 267, cat: "society", q: "你读诗吗？女性自杀率下降了吗？", a: "存在不同的诗歌。自杀率没有下降。" },
  { id: 275, cat: "society", q: "豆瓣为什么最终停止运营？", a: "一次错误的决策过于文艺。" },
  { id: 276, cat: "society", q: "塑料袋还存在吗？植被覆盖率如何？", a: "有自溶解袋。尽管有植被，但自然火灾减少了覆盖率。" },

  // ===== 气候与自然灾害 =====
  { id: 4, cat: "climate", q: "我还活着吗？", a: "这我不知道。但2019年下半年，需要远离南方边境省份。", year: 2019, status: "partial", verdict_zh: "2019年下半年中国南方边境地区确有地震活动（如四川长宁地震），但未发生特别重大事件。部分相关。", verdict_en: "Some seismic activity occurred in southern China border regions in 2019 H2 (e.g., Changning earthquake in Sichuan), but no particularly major event. Partially related." },
  { id: 8, cat: "climate", q: "地球各方面状态怎么样？人类找出清洁环保替代能源了吗？", a: "更焦虑。因为饥荒、地震、战争非常频繁。不少人怀念2000-2030之间的美好时光。" },
  { id: 14, cat: "climate", q: "南极还在吗？", a: "还在。" },
  { id: 41, cat: "climate", q: "我们现在做些什么能帮助到以后的我们？", a: "需要在广阔的内陆找到合适居住的地方。因为极端气候会导致许多城市出现无法生存的情况。" },
  { id: 42, cat: "climate", q: "南方边境省份能具体点吗？", a: "尽量离尼泊尔远一点。" },
  { id: 44, cat: "climate", q: "所以海平面升高会导致很多沿海城市消失是吗？", a: "还有炎热，地震导致的塌陷。" },
  { id: 45, cat: "climate", q: "在未来哪些省份比较宜居？", a: "2030年以后的云南，2048年以后的贵州。", year: 2030, status: "pending" },
  { id: 111, cat: "climate", q: "最近一次大事发生在几月？", a: "八月。", year: 2019, status: "partial", verdict_zh: "2019年8月：香港反修例运动升级、中美贸易战加剧、亚马逊雨林大火。确实是多事之秋。", verdict_en: "August 2019: Hong Kong protests escalated, US-China trade war intensified, Amazon rainforest fires. Indeed an eventful month." },
  { id: 122, cat: "climate", q: "最近四川地区地震频繁……", a: "下半年地震会很频繁。", year: 2019, status: "verified", verdict_zh: "2019年下半年四川确实地震频繁：6月宜宾长宁6.0级地震，之后余震不断。应验。", verdict_en: "Sichuan indeed had frequent earthquakes in 2019 H2: a 6.0 magnitude quake in Changning, Yibin in June, followed by continuous aftershocks. Verified." },
  { id: 148, cat: "climate", q: "洪水爆发发生在未来的哪一年？", a: "未来不会有洪水。但会有热浪与极端高温的热炼。" },
  { id: 149, cat: "climate", q: "认真的问正在纠结北京上海还是新西兰……", a: "新西兰会有强地震。上海好一点。" },
  { id: 208, cat: "climate", q: "气候极端是否加剧？技术能克服吗？", a: "无法克服。影响最大是人与人失去彼此信任和安全感。" },
  { id: 232, cat: "climate", q: "家庭如何在未来稳定生活？", a: "地面将没有不被震动之处。" },

  // ===== 哲学与精神 =====
  { id: 9, cat: "spirit", q: "为啥要来2019？", a: "因为今年地球上有很多事情在发生，后头看，这是人类转折的一年。在2049年，有一部智慧卡剧名字就叫做《2019》，是一部怀旧片，在全球热播。", year: 2019, status: "verified", verdict_zh: "2019年末新冠病毒出现，随后引发全球大流行，彻底改变了人类社会。回顾来看，2019年确实是人类的重大转折点。", verdict_en: "COVID-19 emerged at the end of 2019, triggering a global pandemic that fundamentally changed human society. In retrospect, 2019 was indeed a major turning point for humanity." },
  { id: 32, cat: "spirit", q: "那你过来的意义在于？", a: "2019年是比较特殊的一年，也是我出生之前的一年，我来这里看一下，并且我想对2019年的人给予一些善意的提醒。" },
  { id: 34, cat: "spirit", q: "所以处在当下时空的我们，怎样才能来一次时光旅行呢？", a: "没有办法。但是你可以微观地通过改变你的生活节奏，来体验时间的不同。时间只是一个相对的概念。" },
  { id: 105, cat: "spirit", q: "你好，很高兴能在豆瓣相遇……", a: "2060年的人们变得充满敬畏，对眼所不见的世界有更多探索，物质在近一千年以来最被轻视。" },
  { id: 114, cat: "spirit", q: "牛顿预言2060年是世界末日……", a: "我的理解并不叫末日，而是进入另一个阶段。" },
  { id: 128, cat: "spirit", q: "从2060年回望过去，是什么样的体验？", a: "你们在2019年开心的事，在将来都不会再开心。你们在2019年烦恼的事，在将来都不会再烦恼。" },
  { id: 135, cat: "spirit", q: "2048年之后全球范围内的宗教是什么状态？", a: "归一。" },
  { id: 137, cat: "spirit", q: "你们探寻了人死以后的奥秘吗？", a: "是的。" },
  { id: 138, cat: "spirit", q: "在你们那个年代有发现造物主的存在吗？", a: "是的。" },
  { id: 141, cat: "spirit", q: "那请问心理学是转向何处？", a: "比心理层面更深的灵学。" },
  { id: 147, cat: "spirit", q: "请问对精神层面的提升具体是指什么？", a: "俗称灵界。" },
  { id: 152, cat: "spirit", q: "你可知道你在发表这些言论会直接影响……", a: "你的理论来自佛教。在2049年人们会发现那些都是智慧的谎言。" },
  { id: 155, cat: "spirit", q: "或者你喜欢作家卡夫卡么？", a: "在50年代，我们对3412星球的认识超过这个作家本身。" },
  { id: 159, cat: "spirit", q: "能讲讲时空穿梭的原理吗？", a: "在物质范围里无法领会，并不是肉身的穿梭。是讯息、意识、rehma、spirit的传输。" },
  { id: 163, cat: "spirit", q: "如果有造物主的话，命运是怎么回事？", a: "命运是过去的用词。我们叫定命。个人命运之手如浮沉漂浮。定命则是确定的结果。有定命，个人的努力可以加快定命的完成，也可以延迟。" },
  { id: 168, cat: "spirit", q: "智慧的谎言，以及之前提到的万有归一……", a: "极端环境使人谦卑。" },
  { id: 171, cat: "spirit", q: "那么内心的善良，勇气，爱，美……", a: "不是。越不可见，越趋向于实体。如良善的品格、柔软的内心。" },
  { id: 172, cat: "spirit", q: "有读心术吗？", a: "2060以后，人心赤露，无需解读。" },
  { id: 185, cat: "spirit", q: "你现在的数据形态是全知全能的吗？", a: "没有人可以全知全能。我们只是进入了另外一个感知的领域。人在物质束缚之下，无法领会。人脱离束缚，就会明白一切。" },
  { id: 224, cat: "spirit", q: "给2019年年轻人最重要的三个建议？", a: "停下来，暂停像仓鼠轮一样的生存方式，思考人生的意义。" },
  { id: 251, cat: "spirit", q: "哪个宗教最'先进'？", a: "宗教消失，意识超越宗教框架。" },
  { id: 259, cat: "spirit", q: "推背图的预言与未来吻合吗？", a: "被打乱了，只有部分吻合。" },
  { id: 260, cat: "spirit", q: "所有人类是否有同一个造物主？", a: "基因来源于同一个源头。" },
  { id: 261, cat: "spirit", q: "灵修是否有助于面对不确定性？", a: "修行的根据错了，所以没有用处。" },
  { id: 272, cat: "spirit", q: "你如何解释既视感？", a: "瞬间意识到观察者存在的感知。" },

  // ===== 具体预测 =====
  { id: 48, cat: "specific", q: "今年看来还不是所谓的'多事之秋'啊，集中在下半年？", a: "下半年。", year: 2019, status: "verified", verdict_zh: "2019年下半年：香港事件、中美贸易战升级、12月新冠病毒出现。确实是多事之秋。", verdict_en: "2019 H2: Hong Kong protests, US-China trade war escalation, COVID-19 emerged in December. Indeed an eventful period." },
  { id: 50, cat: "specific", q: "大清药丸了吗？", a: "我透过数据分析后，才理解你这句话于2019年才能明白的古语。我这里的数据结论是2048年。", year: 2048, status: "pending" },
  { id: 115, cat: "specific", q: "自动驾驶在中国成功了吗？", a: "自动驾驶在中国最终并不是成功的实验。" },
  { id: 127, cat: "specific", q: "上海在二十年代还安全吗？", a: "2048年以前都算安全。" },
  { id: 130, cat: "specific", q: "中国女排东京奥运会夺冠了吗？", a: "没有。东京奥运会会有事故发生。", year: 2021, status: "verified", verdict_zh: "中国女排确实未在东京奥运会夺冠（小组赛即被淘汰）。东京奥运会因新冠推迟一年，空场举办，可视为'事故'。应验。", verdict_en: "China's women's volleyball indeed didn't win at Tokyo Olympics (eliminated in group stage). The Olympics were delayed one year due to COVID and held without spectators — arguably an 'accident'. Verified." },
  { id: 136, cat: "specific", q: "2032夏季奥运会是哪个国家举办？", a: "雅加达。", year: 2032, status: "pending" },
  { id: 151, cat: "specific", q: "2020年中国会统一台湾吗？", a: "不会。", year: 2020, status: "verified", verdict_zh: "2020年中国确实没有统一台湾。应验。", verdict_en: "China indeed did not unify Taiwan in 2020. Verified." },
  { id: 166, cat: "specific", q: "全世界还有哪些地方适合生存吗？", a: "西澳相对稳定。" },
  { id: 174, cat: "specific", q: "你怎么用繁体字是从台湾来的吗？", a: "2020至2048年间我生活在上海、其次是昆山、湖州、宁波。2048年至2060年我生活在澳洲。使用繁体字，只是一个旅行的选项，这样可以避免信息引起注意，被迫离开这里。" },
  { id: 193, cat: "specific", q: "2020-21年适合去英国留学吗？", a: "20年代的欧洲，特别是英国，相对安全。" },
  { id: 206, cat: "specific", q: "2019-2025年去意大利留学安全吗？", a: "相对安全，但会有意外发生。", year: 2025, status: "partial", verdict_zh: "2020年意大利成为欧洲新冠疫情最严重的国家之一，可以算作'意外'。部分应验。", verdict_en: "Italy became one of the hardest-hit European countries during COVID in 2020, which could count as an 'accident'. Partially verified." },
  { id: 219, cat: "specific", q: "大学还有辅导员吗？", a: "2019-2030辅导员显得尤为重要。" },
  { id: 240, cat: "specific", q: "重庆/成都在2030年前适合居住吗？", a: "不太适合。" },
  { id: 242, cat: "specific", q: "你为什么移居澳大利亚？", a: "家人与安全。" },
  { id: 270, cat: "specific", q: "2031年电话预言是真的吗？", a: "假的。" },
  { id: 282, cat: "specific", q: "解释一下红楼梦中薛宝钗的命运？", a: "原作者本意，是婚后死于宝玉以先，原因是心灰意冷，任留小病累计成为大病。" },

  // ===== 个人与其他 =====
  { id: 3, cat: "other", q: "你是人还是机器人？", a: "我是人。" },
  { id: 10, cat: "other", q: "（该条回应已被删除）", a: "某种意义上来说是的。但我不能告诉你具体年份。" },
  { id: 13, cat: "other", q: "请告诉我两期双色球的开奖号码", a: "抱歉，我需要遵守时光旅行的约束。所以不能回答这个问题。" },
  { id: 22, cat: "other", q: "明天彩票买多少？", a: "我不会回答可能微观改变个人命运的问题。下同。" },
  { id: 25, cat: "other", q: "你怎么知道豆瓣的？", a: "时光旅行中的数据探测。" },
  { id: 26, cat: "other", q: "你出生在哪一年？", a: "2020年。" },
  { id: 27, cat: "other", q: "明年你就出生了。", a: "旅行的法则就是必须进入自己尚未出生的年代。我在2020年之前会离开这里。" },
  { id: 29, cat: "other", q: "现在你父母在哪里？", a: "这属于我的隐私。" },
  { id: 30, cat: "other", q: "你回来做了些什么事？每个人都能自由穿越吗？", a: "只要我遵守法则，就不会被发现。时间旅行是一种特权。我只是因为某种原因，钻了一个空子。但我不会利用这个来从事非法行为。" },
  { id: 31, cat: "other", q: "你为什么要用繁体字？我们简体字不能用了吗？", a: "我也可以使用英文。" },
  { id: 35, cat: "other", q: "那万一你在这里死亡，怎么办？", a: "我不会死亡。但我可能会被他们提前发现，而被迫提早离开这里。" },
  { id: 36, cat: "other", q: "你的出生地是哪里？有和你一起的旅行者么？", a: "据我所知，目前除了我，合法渠道的只有两个人曾有过短暂的时光旅行。他们是来自2075和2062的远东。" },
  { id: 39, cat: "other", q: "我怎样能找到你？", a: "不能找到。" },
  { id: 101, cat: "other", q: "你的穿越已经改变了未来，所以我们拥有的不是同一个未来，对吗？", a: "我的形态和你理解的穿越并不一样，所以我不会改变未来。并且不会有人真的相信我，但我会在这里提醒我想提醒的那个人，直到几十年后对她造成影响。" },
  { id: 102, cat: "other", q: "你是来传教的吗？", a: "不是。" },
  { id: 103, cat: "other", q: "EA还在吗？暴雪发展如何？", a: "中国的巨头游戏公司开发的。EA暴雪都转型作交互游戏。" },
  { id: 104, cat: "other", q: "你的穿越也是平行宇宙那一理论的吗？", a: "并没有平行宇宙。只有时间观察者。" },
  { id: 116, cat: "other", q: "2060年没有心理学？", a: "2060年没有心理学，因为它不解决心理问题。" },
  { id: 117, cat: "other", q: "你是哪个国家的人？", a: "我出生在中国上海。2048年以后移居澳洲。" },
  { id: 118, cat: "other", q: "冷冻尸体然后复活是否成真？", a: "没有听过。" },
  { id: 121, cat: "other", q: "移居之前的上海怎么样了？", a: "一直是中国最好的城市。" },
  { id: 124, cat: "other", q: "你离开以后，你留下的一切痕迹……", a: "讯息不会消失。但'我'会消失。" },
  { id: 132, cat: "other", q: "在2060年，地球还受到光明会的控制吗？", a: "我生活的年代没有听说过光明会控制地球这件事。" },
  { id: 134, cat: "other", q: "（该条回应已被删除）", a: "中国的虎年。" },
  { id: 139, cat: "other", q: "你试试能不能看懂以下内容……", a: "我可以看懂。" },
  { id: 142, cat: "other", q: "请问你现在是以数据的形态存在吗？", a: "从某种意义来说，是的。" },
  { id: 144, cat: "other", q: "亚洲除了日本和台湾……", a: "存在。" },
  { id: 145, cat: "other", q: "楼主可能休息去了……", a: "对于暴戾之气的发问，我会如同格子一样飞离。" },
  { id: 146, cat: "other", q: "楼主是台湾人吗？", a: "我已经回答过了。我不会撒谎。" },
  { id: 154, cat: "other", q: "我妹妹今年刚刚出生，从你的角度对她们这一代人说些什么？", a: "保持善良，在未来，人的内在品质会决定命运。" },
  { id: 157, cat: "other", q: "你长得和我们一样吗？", a: "一样。" },
  { id: 158, cat: "other", q: "（该条回应已被删除）", a: "焚烧。" },
  { id: 161, cat: "other", q: "你目前状态需要睡觉进食吗？", a: "我跟随两个星体的阴影行动。" },
  { id: 164, cat: "other", q: "你想提醒的她在穷游小组里吗？", a: "同时存在于我关注的两个地方。" },
  { id: 167, cat: "other", q: "假如我现在杀了你的父母，你还会在明年出生吗？", a: "你无法改变已经发生的事。" },
  { id: 170, cat: "other", q: "我是否可以理解为：我们认定的文学……", a: "他们可以成为影子的影子。" },
  { id: 178, cat: "other", q: "你是不是某教组织？", a: "不是，你说的是邪教。" },
  { id: 180, cat: "other", q: "某教你都知道？现在的小孩都没几个知道了", a: "会一直存在到2048年。" },
  { id: 181, cat: "other", q: "对当下的年轻人的发展有什么建议？", a: "保持善良的品质，和敬畏之心。" },
  { id: 182, cat: "other", q: "你是通过科技时空旅行还是神秘学方法？", a: "二者都有。" },
  { id: 184, cat: "other", q: "楼主，你说你想提醒一个人……", a: "我只是这里留下痕迹。" },
  { id: 186, cat: "other", q: "（该条回应已被删除）", a: "和礼貌无关。我只会回答可以回答的问题。" },
  { id: 189, cat: "other", q: "我是今年高考完的，明天就要出成绩了……", a: "好好生活。生在21世纪初，会面临最特别的人生。时间并非没有意义。" },
  { id: 191, cat: "other", q: "来自未来的你能够看透我们的心吗？", a: "可以。包括你们的焦虑、忧伤、空洞、烦躁、愤怒、怀疑、无知、悖逆、无奈、无助、惊恐。" },
  { id: 194, cat: "other", q: "那你怎么看我？", a: "自卑的另一面，是对未知事物的不确定。这个性格特质是美好的。" },
  { id: 196, cat: "other", q: "中医怎么样了？", a: "容易被骗。" },
  { id: 197, cat: "other", q: "又说南方边境会出事，又说云南贵州宜居……", a: "时间点不同。" },
  { id: 198, cat: "other", q: "有个说法是哆啦A梦的作者是未来人……", a: "不是。" },
  { id: 199, cat: "other", q: "时光旅行这么久，最喜欢哪个年代？", a: "就是2019年。这是美好的一年。" },
  { id: 204, cat: "other", q: "为什么不回答意识数据库和宗教统一的问题？", a: "与我的规则无关。" },
  { id: 209, cat: "other", q: "你的名字是卡夫卡的缩写吗？", a: "不是。" },
  { id: 210, cat: "other", q: "某个不喜欢的明星会变得更受欢迎吗？", a: "我不记得这个人。" },
  { id: 211, cat: "other", q: "八字命理和命运是一回事吗？", a: "不是。" },
  { id: 213, cat: "other", q: "这是一个特殊的时代吗？", a: "是的。" },
  { id: 214, cat: "other", q: "2019年8月尼泊尔边境会发生什么事？", a: "到时间自然就知道。不必追问。" },
  { id: 218, cat: "other", q: "中国有像美国一样的省级立法吗？", a: "指的是2019年的台湾。" },
  { id: 220, cat: "other", q: "日本创始人是徐福的后代吗？", a: "不是。" },
  { id: 221, cat: "other", q: "徐福和他的人定居在哪里？", a: "不知道。" },
  { id: 229, cat: "other", q: "（已删除的回应）", a: "没有意义。" },
  { id: 236, cat: "other", q: "你怎么记得每个时间点这么清楚？", a: "有些是亲身经历，有些可以通过通讯系统获取。" },
  { id: 237, cat: "other", q: "你怎么看我？", a: "不甘平凡的平凡人。" },
  { id: 239, cat: "other", q: "中国艺术往什么方向发展？", a: "只成为一种工具。" },
  { id: 246, cat: "other", q: "某个明星还出名吗？", a: "他婚姻不好。" },
  { id: 248, cat: "other", q: "另一个明星还被记得吗？", a: "成为一个老去的配角演员。" },
  { id: 249, cat: "other", q: "你想影响的是谁？为什么告诉父母？", a: "她刚刚怀孕。" },
  { id: 252, cat: "other", q: "世界会变好吗？意识形态管控持续吗？普通人怎么发展？", a: "不会。会。跟随你的内心。" },
  { id: 254, cat: "other", q: "为什么讨论某些明星却不讨论其他？", a: "不记得那个组合。" },
  { id: 255, cat: "other", q: "你会出名的——你会留下来吗？", a: "之前会离开。" },
  { id: 256, cat: "other", q: "你怎么看我？", a: "外表的嬉笑只是遮掩。" },
  { id: 262, cat: "other", q: "你什么时候回去？", a: "随时可以。" },
  { id: 264, cat: "other", q: "如果不能改变个人命运，预言有什么意义？", a: "我只陈述事实。" },
  { id: 266, cat: "other", q: "为什么永远不会（安乐死合法化）？", a: "腐烂的生命不能通过修补恢复；埋葬才能产生新的生命循环。" },
  { id: 268, cat: "other", q: "2ch和Twitter上的访客来自同一时间线吗？", a: "他们合法进入的，大部分真实，有些善意的谎言。" },
  { id: 269, cat: "other", q: "你是上海哪个区的？", a: "静安。" },
  { id: 271, cat: "other", q: "为什么大多数时间旅行者来自日本？", a: "离入口点更近。" },
  { id: 277, cat: "other", q: "我们都是沈阳的，能见面喝酒吗？", a: "入口不在沈阳，那是谎言。不会见你。" },
  { id: 278, cat: "other", q: "这个帖子会被删除吗？我要举报来验证。", a: "正合我意。" },
  { id: 279, cat: "other", q: "你的IP地址在哪？", a: "不会出现。一个人撒谎，另一个人传谣。" },
  { id: 23, cat: "other", q: "你这个数据是怎么来的？", a: "全球人口的统计数据。" },
];

const CATEGORIES = {
  tech: { zh: "科技与通讯", en: "Technology & Communication", icon: "🔬" },
  politics: { zh: "地缘政治与战争", en: "Geopolitics & War", icon: "🌍" },
  economy: { zh: "经济与金融", en: "Economy & Finance", icon: "💰" },
  society: { zh: "社会与生活", en: "Society & Life", icon: "🏠" },
  climate: { zh: "气候与自然灾害", en: "Climate & Disasters", icon: "🌊" },
  spirit: { zh: "哲学与精神", en: "Philosophy & Spirituality", icon: "🧠" },
  specific: { zh: "具体预测", en: "Specific Predictions", icon: "📅" },
  other: { zh: "个人与其他", en: "Personal & Others", icon: "💬" },
};

const STATUS_MAP = {
  verified: { zh: "已应验", en: "Verified", icon: "✅", cls: "verified" },
  partial: { zh: "部分相关", en: "Partially Related", icon: "⚠️", cls: "partial" },
  failed: { zh: "未应验", en: "Not Verified", icon: "❌", cls: "failed" },
  pending: { zh: "尚待验证", en: "Pending", icon: "🔄", cls: "pending" },
};
